name: "Ordinary PHP Code Quality"
on:
  push:
    branches:
      - dev
    tags:
      - '**'
permissions:
  packages: read
jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Test code quality
    steps:
      - name: Quality Tests
        id: quality
        uses: OrdinaryPHP/code-quality@dev
