name: "Ordinary PHP Code Quality"
on:
  push:
    branches:
      - dev
    tags:
      - '**'
permissions:
  packages: read
jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ "8.2", "8.3" ]
    steps:
      - uses: actions/checkout@main
      - uses: ordinaryphp/code-quality@dev
        with:
          php_version: ${{ matrix.php-version }}
