name: "Ordinary PHP Code Quality"
on:
  push:
    branches:
      - dev
    tags:
      - '**'
permissions:
  packages: read
jobs:
  code-quality:
    strategy:
      matrix:
        php-version: [ "8.2", "8.3" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ordinaryphp/code-quality-action@0.1.0
        with:
          version: 0.2.0
          phpVersion: ${{ matrix.php-version }}
