name: "Ordinary PHP Code Quality"
on:
  push:
    branches:
      - dev
    tags:
      - '**'
permissions:
  packages: read
jobs:
  code-quality:
    strategy:
      matrix:
        php-version: [ "8.2", "8.3" ]
    uses: ordinaryphp/workflows/.github/workflows/lib-testing-and-quality.yaml@dev
    with:
      phpVersion: ${{ matrix.php-version }}
